// Generated by typelizer — do not edit.
// Source: MyAppWeb.DashboardController

import type { SharedProps } from "../shared.props";

export interface SettingsProfileEditProps extends SharedProps {}
