defmodule Typelizer.Output do
  @moduledoc false
  # Writes generated files, deletes stale ones, and compares them with the disk.
  # Only files that start with the typelizer header are ever overwritten or deleted.

  alias Typelizer.{GenerationError, TS}

  @type change ::
          {:changed, String.t(), String.t(), String.t()}
          | {:missing, String.t()}
          | {:stale, String.t()}

  @doc """
  Writes the outputs. Returns `%{written: n, unchanged: n, removed: n}`.
  Raises before writing anything when a target file was not generated by typelizer.
  """
  @spec write([Typelizer.Generator.output()]) :: %{
          written: non_neg_integer(),
          unchanged: non_neg_integer(),
          removed: non_neg_integer()
        }
  def write(outputs) do
    Enum.each(outputs, &check_conflicts!/1)

    Enum.reduce(outputs, %{written: 0, unchanged: 0, removed: 0}, fn output, acc ->
      acc = Enum.reduce(output.files, acc, &write_file(output.dir, &1, &2))

      Enum.reduce(stale(output), acc, fn path, acc ->
        File.rm!(path)
        remove_empty_dirs(Path.dirname(path), output.dir)
        %{acc | removed: acc.removed + 1}
      end)
    end)
  end

  @doc "Compares the outputs with the disk. Returns the changes, sorted by path."
  @spec diff([Typelizer.Generator.output()]) :: [change()]
  def diff(outputs) do
    outputs
    |> Enum.flat_map(fn output ->
      changes = Enum.flat_map(output.files, &file_change(output.dir, &1))
      changes ++ Enum.map(stale(output), &{:stale, &1})
    end)
    |> Enum.sort_by(&elem(&1, 1))
  end

  defp file_change(dir, {relative, content}) do
    path = Path.join(dir, relative)

    case File.read(path) do
      {:ok, ^content} -> []
      {:ok, current} -> [{:changed, path, current, content}]
      {:error, _} -> [{:missing, path}]
    end
  end

  @doc "A short, readable report of the changes, with paths relative to `root`."
  @spec report([change()], String.t()) :: String.t()
  def report(changes, root) do
    count = length(changes)

    lines =
      Enum.map(changes, fn
        {:changed, path, current, content} ->
          "  changed  #{relative(path, root)}\n" <> line_diff(current, content)

        {:missing, path} ->
          "  missing  #{relative(path, root)}"

        {:stale, path} ->
          "  stale    #{relative(path, root)}"
      end)

    Enum.join(
      ["typelizer: the generated TypeScript is out of date (#{count} #{files(count)}):" | lines] ++
        ["Run `mix typelizer.gen` and commit the result."],
      "\n"
    )
  end

  @doc "`1 file`, `2 files`."
  @spec files(non_neg_integer()) :: String.t()
  def files(1), do: "file"
  def files(_count), do: "files"

  defp write_file(dir, {relative, content}, acc) do
    path = Path.join(dir, relative)

    case File.read(path) do
      {:ok, ^content} ->
        %{acc | unchanged: acc.unchanged + 1}

      _ ->
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, content)
        %{acc | written: acc.written + 1}
    end
  end

  defp check_conflicts!(output) do
    Enum.each(output.files, fn {relative, _content} ->
      path = Path.join(output.dir, relative)

      if File.exists?(path) and not generated_file?(path) do
        raise GenerationError,
              "#{path} exists and was not generated by typelizer. Move it, or change " <>
                "config :typelizer, output: [#{output.kind}: ...]"
      end
    end)
  end

  defp stale(output) do
    generated = MapSet.new(Map.keys(output.files), &Path.join(output.dir, &1))

    output.dir
    |> Path.join("**/*.ts")
    |> Path.wildcard()
    |> Enum.reject(&MapSet.member?(generated, &1))
    |> Enum.filter(&generated_file?/1)
    |> Enum.sort()
  end

  defp generated_file?(path) do
    case File.open(path, [:read, :utf8], &IO.read(&1, :line)) do
      {:ok, line} when is_binary(line) -> TS.generated?(line)
      _ -> false
    end
  end

  defp remove_empty_dirs(dir, root) do
    if dir != root and String.starts_with?(dir, root) and File.ls(dir) == {:ok, []} do
      File.rmdir!(dir)
      remove_empty_dirs(Path.dirname(dir), root)
    end
  end

  defp line_diff(current, content) do
    lines =
      current
      |> String.split("\n")
      |> List.myers_difference(String.split(content, "\n"))
      |> Enum.flat_map(fn
        {:eq, _} -> []
        {:del, lines} -> Enum.map(lines, &"    - #{&1}")
        {:ins, lines} -> Enum.map(lines, &"    + #{&1}")
      end)

    {shown, hidden} = Enum.split(lines, 20)
    more = if hidden == [], do: [], else: ["    … #{length(hidden)} more lines"]
    Enum.join(shown ++ more, "\n")
  end

  defp relative(path, root), do: Path.relative_to(path, root)
end
