defmodule Typelizer.TS do
  @moduledoc false
  # Writes TypeScript source text. The output style is fixed: two-space indentation,
  # double quotes, semicolons, trailing commas in multi-line literals.

  alias Typelizer.{Naming, TypeSpec}

  @header "// Generated by typelizer — do not edit."

  # The line width of the output, as in Prettier's default configuration.
  @width 80

  @doc "The maximum line width of the generated code."
  @spec width() :: pos_integer()
  def width, do: @width

  @doc "The first line of every generated file."
  @spec header() :: String.t()
  def header, do: @header

  @doc "True when `content` starts with the typelizer header."
  @spec generated?(String.t()) :: boolean()
  def generated?(content), do: String.starts_with?(content, @header)

  @doc """
  Builds a whole file: the header, an optional `Source:` line, then the sections
  separated by blank lines. Empty sections are skipped. Ends with one newline.
  """
  @spec file(String.t() | nil, [String.t() | nil]) :: String.t()
  def file(source, sections) do
    head = if source, do: "#{@header}\n// Source: #{source}", else: @header

    [head | sections]
    |> Enum.reject(&(&1 in [nil, ""]))
    |> Enum.map_join("\n\n", &String.trim_trailing/1)
    |> Kernel.<>("\n")
  end

  @doc """
  Renders an internal type spec. `name_of` maps a serializer module to its interface
  name. `level` is the indentation level of the line that holds the type.
  """
  @spec type(TypeSpec.t(), (module() -> String.t()), non_neg_integer()) :: String.t()
  def type(spec, name_of, level \\ 0)
  def type(:string, _name_of, _level), do: "string"
  def type(:number, _name_of, _level), do: "number"
  def type(:boolean, _name_of, _level), do: "boolean"
  def type(:temporal, _name_of, _level), do: "string"
  def type(:map, _name_of, _level), do: "Record<string, unknown>"
  def type(:any, _name_of, _level), do: "any"
  def type(:unknown, _name_of, _level), do: "unknown"
  def type({:decimal, :string}, _name_of, _level), do: "string"
  def type({:decimal, :number}, _name_of, _level), do: "number"
  def type({:enum, values}, _name_of, _level), do: Enum.map_join(values, " | ", &literal/1)
  def type({:ts, raw}, _name_of, _level), do: raw
  def type({:serializer, module}, name_of, _level), do: name_of.(module)

  def type({:nullable, spec}, name_of, level), do: type(spec, name_of, level) <> " | null"
  def type({:record, spec}, name_of, level), do: "Record<string, #{type(spec, name_of, level)}>"
  def type({:list, spec}, name_of, level), do: element(spec, name_of, level) <> "[]"
  def type({:object, []}, _name_of, _level), do: "Record<string, never>"

  def type({:object, props}, name_of, level) do
    "{\n" <> props(props, name_of, level + 1) <> indent(level) <> "}"
  end

  @doc """
  Renders prop lines (`  key: T;` or `  key?: T;`), one per line, each ending in a
  newline. A prop is `{key, spec, optional?}` or the internal 4-tuple.
  """
  @spec props([tuple()], (module() -> String.t()), non_neg_integer()) :: String.t()
  def props(props, name_of, level) do
    Enum.map_join(props, fn prop ->
      {key, spec, optional} = prop_parts(prop)
      mark = if optional, do: "?", else: ""
      head = indent(level) <> property_key(key) <> mark <> ":"
      line = head <> " " <> type(spec, name_of, level) <> ";"

      cond do
        not String.contains?(line, "\n") and String.length(line) <= @width -> line <> "\n"
        members = union_members(spec, name_of, level + 2) -> broken_union(head, members, level)
        true -> line <> "\n"
      end
    end)
  end

  # A long union breaks into one member per line, the way Prettier prints it:
  #
  #   status:
  #     | "todo"
  #     | "done";
  defp broken_union(head, members, level) do
    head <> "\n" <> Enum.map_join(members, "\n", &(indent(level + 1) <> "| " <> &1)) <> ";\n"
  end

  defp union_members({:nullable, {:list, {:object, _}} = spec}, name_of, level),
    do: [type(spec, name_of, level), "null"]

  defp union_members({:nullable, {:enum, values}}, _name_of, _level),
    do: Enum.map(values, &literal/1) ++ ["null"]

  defp union_members({:enum, [_, _ | _] = values}, _name_of, _level),
    do: Enum.map(values, &literal/1)

  defp union_members(_spec, _name_of, _level), do: nil

  defp prop_parts({_name, key, spec, optional}), do: {key, spec, optional}
  defp prop_parts({key, spec, optional}), do: {key, spec, optional}

  @doc "A property name, quoted when it is not a valid identifier."
  @spec property_key(String.t()) :: String.t()
  def property_key(key) do
    if Naming.identifier?(key), do: key, else: literal(key)
  end

  @doc "A TypeScript string or number literal."
  @spec literal(String.t() | integer()) :: String.t()
  def literal(value) when is_integer(value), do: Integer.to_string(value)

  def literal(value) when is_binary(value) do
    escaped =
      value
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")
      |> String.replace("\n", "\\n")

    "\"" <> escaped <> "\""
  end

  @doc "Indentation for a level."
  @spec indent(non_neg_integer()) :: String.t()
  def indent(level), do: String.duplicate("  ", level)

  @doc """
  A relative module specifier from the directory `from_dir` to `to_path` (both
  absolute), without extension: `"./Task"`, `"../serializers/Task"`.
  """
  @spec relative(String.t(), String.t()) :: String.t()
  def relative(from_dir, to_path) do
    {from_rest, to_rest} = drop_common(Path.split(from_dir), Path.split(to_path))

    case Enum.map(from_rest, fn _ -> ".." end) ++ to_rest do
      [".." | _] = parts -> Enum.join(parts, "/")
      parts -> Enum.join(["." | parts], "/")
    end
  end

  defp drop_common([same | from], [same | to]), do: drop_common(from, to)
  defp drop_common(from, to), do: {from, to}

  @doc """
  An export statement with a list of names, on one line when it fits in 80
  columns, one name per line otherwise: `export { a, b };`.
  """
  @spec export_list(String.t(), [String.t()]) :: String.t()
  def export_list(keyword, names) do
    line = "#{keyword} { #{Enum.join(names, ", ")} };"

    if String.length(line) <= 80 do
      line
    else
      "#{keyword} {\n" <> Enum.map_join(names, &"  #{&1},\n") <> "};"
    end
  end

  defp element(spec, name_of, level) do
    rendered = type(spec, name_of, level)

    if needs_parens?(spec), do: "(" <> rendered <> ")", else: rendered
  end

  defp needs_parens?({:enum, [_, _ | _]}), do: true
  defp needs_parens?({:nullable, _}), do: true
  defp needs_parens?({:ts, raw}), do: String.contains?(raw, " ")
  defp needs_parens?(_spec), do: false
end
