// Generated by typelizer — do not edit.
// Source: MyAppWeb.Admin.TaskSerializer

export interface AdminTask {
  id: string;
  title: string | null;
  assignee_id: string | null;
  updated_at: string;
}
