// Generated by typelizer — do not edit.
// Source: MyAppWeb.Admin.TaskSerializer

import type { Envelope } from "./Envelope";

export interface AdminTask {
  id: string;
  title: string | null;
  assignee_id: string | null;
  updated_at: string;
  history_page: Envelope<string[], { page_count: number }>;
}
