// Generated by typelizer — do not edit.
// Source: MyAppWeb.CategorySerializer

import type { Project } from "./Project";

export interface Category {
  id: number;
  name: string;
  opensAt: string | null;
  rates: Record<string, string>;
  parent: Category | null;
  children: Category[];
  projects: Project[];
}
