// Generated by typelizer — do not edit.
// Source: MyAppWeb.CommentSerializer

import type { Task } from "./Task";
import type { User } from "./User";

export interface Comment {
  id: number;
  body: string;
  insertedAt: string;
  author: User;
  task: Task | null;
}
