// Generated by typelizer — do not edit.
// Source: MyAppWeb.StatsSerializer

import type { Envelope } from "./Envelope";
import type { Project } from "./Project";
import type { User } from "./User";

export interface DashboardStats {
  openCount: number;
  byStatus: Record<string, number>;
  lastActivityAt: string | null;
  window: {
    from: string;
    to: string;
    label?: string;
  };
  trend: ("up" | "down" | "flat")[];
  raw: Array<[string, number]>;
  mixed: (string | number)[];
  subject: User | Project;
  ownerCard: Omit<User, "role"> & { online: boolean };
  reviewer:
    | (User & {
        admin: boolean;
      })
    | null;
  history: (string | 1 | 2)[];
  latestUsers: Envelope<User[], { generatedAt: string }>;
  owner: User | null;
}
