// Generated by typelizer — do not edit.
// Source: MyAppWeb.StatsSerializer

import type { User } from "./User";

export interface DashboardStats {
  openCount: number;
  byStatus: Record<string, number>;
  lastActivityAt: string | null;
  window: {
    from: string;
    to: string;
    label?: string;
  };
  trend: ("up" | "down" | "flat")[];
  raw: Array<[string, number]>;
  owner: User | null;
}
