// Generated by typelizer — do not edit.

/** Data wrapped in an envelope, with optional metadata. */
export interface Envelope<T, M = Record<string, unknown>> {
  data: T;
  meta?: M;
}

export interface PaginationMeta {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

/** One page of a list, with page-based pagination metadata. */
export interface Paginated<T> {
  data: T[];
  meta: PaginationMeta;
}

export interface CursorMeta {
  nextCursor: string | null;
  previousCursor: string | null;
}

/** One page of a list, with cursor pagination metadata. */
export interface CursorPaginated<T> {
  data: T[];
  meta: CursorMeta;
}
