// Generated by typelizer — do not edit.
// Source: MyAppWeb.ProjectSerializer

import type { Task } from "./Task";

export interface Project {
  id: string;
  name: string;
  budget: string | null;
  settings: {
    theme: "light" | "dark" | null;
    notifyOnDone: boolean | null;
  } | null;
  links: {
    id: string;
    url: string | null;
    label: string | null;
  }[];
  address: {
    street: string;
    line2: string | null;
    city: string;
    geo: {
      lat: number;
      lng: number;
    };
  } | null;
  price: {
    amount: number;
    currency: string;
  };
  tasks: Task[];
}
