// Generated by typelizer — do not edit.
// Source: MyAppWeb.ProjectSerializer

import type { Task } from "./Task";

export interface Project {
  id: string;
  name: string;
  budget: string | null;
  settings: {
    theme: "light" | "dark" | null;
    notifyOnDone: boolean | null;
  } | null;
  links: {
    id: string;
    url: string | null;
    label: string | null;
  }[];
  tasks: Task[];
}
