// Generated by typelizer — do not edit.
// Source: MyAppWeb.TaskSerializer

import type { Comment } from "./Comment";
import type { Project } from "./Project";
import type { User } from "./User";

export interface Task {
  id: string;
  status: "todo" | "doing" | "done";
  priority: "low" | "high" | null;
  labels: ("bug" | "feature")[];
  dueOn: string | null;
  estimate: string | null;
  position: number;
  title: string;
  doneAt: string | null;
  metadata: Record<string, unknown>;
  scores: Record<string, number> | null;
  tags: string[];
  insertedAt: string;
  overdue: boolean;
  canEdit: boolean;
  summary: string;
  dueLabel: string | null;
  assignee: User | null;
  comments: Comment[];
  archivedNote?: string;
  internalRank?: number | null;
  project?: Project;
  watchers?: User[];
}
