defmodule Typelizer.GoldenTest do
  # Compares the output for the fixture app in test/support with test/golden, byte for
  # byte. Regenerate on purpose with `UPDATE_GOLDEN=1 mix test` and review the diff.
  use ExUnit.Case, async: true

  alias Typelizer.{Generator, Golden, Output}

  test "the generated files match test/golden" do
    outputs = Generator.generate(Golden.config())

    if System.get_env("UPDATE_GOLDEN") == "1" do
      Output.write(outputs)
    end

    for %{dir: dir, files: files} <- outputs do
      on_disk =
        dir
        |> Path.join("**/*.ts")
        |> Path.wildcard()
        |> Enum.map(&Path.relative_to(&1, dir))
        |> Enum.sort()

      assert on_disk == Enum.sort(Map.keys(files)), "the files in #{dir} differ"

      for {relative, content} <- files do
        assert File.read!(Path.join(dir, relative)) == content,
               "#{relative} differs from the golden file. Run UPDATE_GOLDEN=1 mix test " <>
                 "and review the diff"
      end
    end

    assert Enum.map(outputs, & &1.kind) == [:serializers, :routes, :pages]
  end

  test "the output is deterministic" do
    assert Generator.generate(Golden.config()) == Generator.generate(Golden.config())
  end

  test "every file starts with the header and ends with one newline" do
    for %{files: files} <- Generator.generate(Golden.config()), {_path, content} <- files do
      assert String.starts_with?(content, "// Generated by typelizer — do not edit.\n")
      assert String.ends_with?(content, "\n")
      refute String.ends_with?(content, "\n\n")
    end
  end
end
