// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const apiV1Project = {
  /** GET /api/v1/projects */
  index: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/api/v1/projects", {}, options),
    method: "get",
  }),
  /** GET /api/v1/projects/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/api/v1/projects/:id", params, options),
    method: "get",
  }),
  /** PATCH /api/v1/projects/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"patch"> => ({
    url: buildUrl("/api/v1/projects/:id", params, options),
    method: "patch",
  }),
} as const;
