// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const apiV1Member = {
  /** GET /api/v1/projects/:project_id/members/:member_id */
  show: (
    params: { projectId: string | number; memberId: string | number },
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl(
      "/api/v1/projects/:project_id/members/:member_id",
      params,
      options,
    ),
    method: "get",
  }),
} as const;
