// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const board = {
  /** GET /board/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/board/:id/edit", params, options),
    method: "get",
  }),
  /** GET /board */
  index: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/board", {}, options),
    method: "get",
  }),
} as const;
