// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const file = {
  /** GET /files/*path */
  show: (
    params: { path: string | string[] } | string | string[],
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/files/*path", params, options),
    method: "get",
  }),
} as const;
