// Generated by typelizer — do not edit.

import { apiV1Member } from "./apiV1Member";
import { apiV1Project } from "./apiV1Project";
import { board } from "./board";
import { file } from "./file";
import { page } from "./page";
import { task } from "./task";
import { taskComment } from "./taskComment";

export { apiV1Member, apiV1Project, board, file, page, task, taskComment };
export { buildUrl, setRoutesBaseUrl } from "./runtime";
export type { Method, RouteDefinition, RouteOptions } from "./runtime";

export const routes = {
  apiV1Member,
  apiV1Project,
  board,
  file,
  page,
  task,
  taskComment,
} as const;
