// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const localizedPage = {
  /** GET /:locale/articles/:slug */
  article: (
    params:
      { locale?: string | number; slug: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/:locale/articles/:slug", params, options, "slug"),
    method: "get",
  }),
  /** GET /:locale */
  index: (
    params?: { locale?: string | number },
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/:locale", params ?? {}, options),
    method: "get",
  }),
} as const;
