// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const localizedFile = {
  /** GET /:locale/sections/:section/*path */
  show: (
    params: {
      locale?: string | number;
      section: string | number;
      path: string | string[];
    },
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/:locale/sections/:section/*path", params, options),
    method: "get",
  }),
} as const;
