// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const page = {
  /** GET /about */
  about: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/about", {}, options),
    method: "get",
  }),
  /** GET / */
  home: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/", {}, options),
    method: "get",
  }),
} as const;
