// Generated by typelizer — do not edit.

export type Method = "get" | "post" | "put" | "patch" | "delete";

export interface RouteDefinition<M extends Method = Method> {
  url: string;
  method: M;
}

export interface RouteOptions<Q extends object = Record<string, unknown>> {
  query?: Q;
  anchor?: string;
}

type ParamValue = string | number | string[];

export type UrlDefaults = Record<string, unknown>;

let routesBaseUrl = "";
let urlDefaults: UrlDefaults | (() => UrlDefaults) = {};

/**
 * Prefixes every generated URL with an origin, for example
 * "https://app.example.com". Pass "" to go back to relative URLs.
 */
export function setRoutesBaseUrl(url: string): void {
  routesBaseUrl = url.replace(/\/+$/, "");
}

/**
 * Sets values for path params that many routes share, such as a locale. Pass a
 * function to read the current values on every call. A param given to a helper
 * wins over its default.
 */
export function setUrlDefaults(
  defaults: UrlDefaults | (() => UrlDefaults),
): void {
  urlDefaults = defaults;
}

/** Adds one URL default and keeps the others. */
export function addUrlDefault(key: string, value: unknown): void {
  const current = urlDefaults;
  urlDefaults =
    typeof current === "function"
      ? () => ({ ...current(), [key]: value })
      : { ...current, [key]: value };
}

const PARAM = /([:*])([A-Za-z_][A-Za-z0-9_]*)/g;

/**
 * Builds a URL from a path template such as "/tasks/:id". A single value (not an
 * object) is the value of `scalarParam`, or of the first param of the template.
 */
export function buildUrl(
  template: string,
  params: Record<string, unknown> | ParamValue,
  options?: RouteOptions<object>,
  scalarParam?: string,
): string {
  const values = toParamObject(template, params, scalarParam);
  const defaults =
    typeof urlDefaults === "function" ? urlDefaults() : urlDefaults;
  const path = template.replace(PARAM, (_match, kind: string, name: string) =>
    encodeParam(kind === "*", paramValue(values, defaults, name, template)),
  );
  const query = options?.query ? encodeQuery(options.query) : "";

  return (
    routesBaseUrl +
    path +
    (query ? `?${query}` : "") +
    (options?.anchor ? `#${encodeURIComponent(options.anchor)}` : "")
  );
}

function toParamObject(
  template: string,
  params: Record<string, unknown> | ParamValue,
  scalarParam?: string,
): Record<string, unknown> {
  if (typeof params === "object" && !Array.isArray(params)) return params;
  const name = scalarParam ?? new RegExp(PARAM.source).exec(template)?.[2];
  return name ? { [name]: params } : {};
}

// Path params accept the snake_case name of the router and its camelCase form.
// A given value wins over a URL default.
function paramValue(
  values: Record<string, unknown>,
  defaults: UrlDefaults,
  name: string,
  template: string,
): unknown {
  const camel = name.replace(/_([a-z0-9])/g, (_m, c: string) =>
    c.toUpperCase(),
  );
  const value = lookup(values, name, camel) ?? lookup(defaults, name, camel);
  if (value === undefined || value === null) {
    throw new Error(
      `typelizer: missing route param "${camel}" for ${template}`,
    );
  }
  return value;
}

function lookup(
  values: Record<string, unknown>,
  name: string,
  camel: string,
): unknown {
  return name in values ? values[name] : values[camel];
}

function encodeParam(glob: boolean, value: unknown): string {
  if (!glob) return encodeURIComponent(String(value));
  const parts = Array.isArray(value) ? value : String(value).split("/");
  return parts.map((part) => encodeURIComponent(String(part))).join("/");
}

// Plug conventions: arrays of scalars become key[]=v, objects become key[sub]=v,
// arrays of objects become key[0][sub]=v (as Phoenix forms send them), dates
// become ISO-8601 strings, and null or undefined values are left out.
function encodeQuery(query: object): string {
  const parts: string[] = [];
  for (const [key, value] of Object.entries(query)) {
    appendQuery(parts, encodeURIComponent(key), value);
  }
  return parts.join("&");
}

function appendQuery(parts: string[], key: string, value: unknown): void {
  if (value === undefined || value === null) return;

  if (value instanceof Date) {
    parts.push(`${key}=${encodeURIComponent(value.toISOString())}`);
  } else if (Array.isArray(value)) {
    const indexed = value.some(
      (item) =>
        typeof item === "object" && item !== null && !(item instanceof Date),
    );
    value.forEach((item, index) =>
      appendQuery(parts, indexed ? `${key}[${index}]` : `${key}[]`, item),
    );
  } else if (typeof value === "object") {
    for (const [name, item] of Object.entries(value)) {
      appendQuery(parts, `${key}[${encodeURIComponent(name)}]`, item);
    }
  } else {
    parts.push(`${key}=${encodeURIComponent(String(value))}`);
  }
}
