// Generated by typelizer — do not edit.

export type Method = "get" | "post" | "put" | "patch" | "delete";

export interface RouteDefinition<M extends Method = Method> {
  url: string;
  method: M;
}

export interface RouteOptions {
  query?: Record<string, unknown>;
  anchor?: string;
}

type ParamValue = string | number | string[];

let routesBaseUrl = "";

/**
 * Prefixes every generated URL with an origin, for example
 * "https://app.example.com". Pass "" to go back to relative URLs.
 */
export function setRoutesBaseUrl(url: string): void {
  routesBaseUrl = url.replace(/\/+$/, "");
}

const PARAM = /([:*])([A-Za-z_][A-Za-z0-9_]*)/g;

/** Builds a URL from a path template such as "/tasks/:id". */
export function buildUrl(
  template: string,
  params: Record<string, unknown> | ParamValue,
  options?: RouteOptions,
): string {
  const values = toParamObject(template, params);
  const path = template.replace(PARAM, (_match, kind: string, name: string) =>
    encodeParam(kind === "*", paramValue(values, name, template)),
  );
  const query = options?.query ? encodeQuery(options.query) : "";

  return (
    routesBaseUrl +
    path +
    (query ? `?${query}` : "") +
    (options?.anchor ? `#${options.anchor}` : "")
  );
}

function toParamObject(
  template: string,
  params: Record<string, unknown> | ParamValue,
): Record<string, unknown> {
  if (typeof params === "object" && !Array.isArray(params)) return params;
  const name = new RegExp(PARAM.source).exec(template)?.[2];
  return name ? { [name]: params } : {};
}

// Path params accept the snake_case name of the router and its camelCase form.
function paramValue(
  values: Record<string, unknown>,
  name: string,
  template: string,
): unknown {
  const camel = name.replace(/_([a-z0-9])/g, (_m, c: string) =>
    c.toUpperCase(),
  );
  const value = name in values ? values[name] : values[camel];
  if (value === undefined || value === null) {
    throw new Error(
      `typelizer: missing route param "${camel}" for ${template}`,
    );
  }
  return value;
}

function encodeParam(glob: boolean, value: unknown): string {
  if (!glob) return encodeURIComponent(String(value));
  const parts = Array.isArray(value) ? value : String(value).split("/");
  return parts.map((part) => encodeURIComponent(String(part))).join("/");
}

// Plug conventions: arrays become key[]=v, nested objects become key[sub]=v.
function encodeQuery(query: Record<string, unknown>, prefix?: string): string {
  const parts: string[] = [];

  for (const [rawKey, value] of Object.entries(query)) {
    const key = prefix
      ? `${prefix}[${encodeURIComponent(rawKey)}]`
      : encodeURIComponent(rawKey);

    if (value === undefined || value === null) continue;

    if (Array.isArray(value)) {
      for (const item of value) {
        if (item === undefined || item === null) continue;
        parts.push(`${key}[]=${encodeURIComponent(String(item))}`);
      }
    } else if (typeof value === "object") {
      const nested = encodeQuery(value as Record<string, unknown>, key);
      if (nested) parts.push(nested);
    } else {
      parts.push(`${key}=${encodeURIComponent(String(value))}`);
    }
  }

  return parts.join("&");
}
