// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export const taskComment = {
  /** POST /tasks/:task_id/comments */
  create: (
    params: { taskId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"post"> => ({
    url: buildUrl("/tasks/:task_id/comments", params, options),
    method: "post",
  }),
  /** GET /tasks/:task_id/comments */
  index: (
    params: { taskId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/tasks/:task_id/comments", params, options),
    method: "get",
  }),
} as const;
