// Generated by typelizer — do not edit.

import { buildUrl, type RouteDefinition, type RouteOptions } from "./runtime";

export type TaskEditQuery = Record<string, never>;

export type TaskIndexQuery = {
  page?: number;
  status?: "todo" | "doing" | "done";
  tags?: string[];
  due_before?: string;
  updated_after?: string | Date;
  min_estimate?: string | number;
  filter?: {
    owner_id: number;
    archived?: boolean;
  };
  sort?: {
    field: string;
    dir: "asc" | "desc";
  }[];
};

export type TaskShowQuery = {
  include: ("comments" | "assignee")[];
};

export const task = {
  /** POST /tasks */
  create: (options?: RouteOptions): RouteDefinition<"post"> => ({
    url: buildUrl("/tasks", {}, options),
    method: "post",
  }),
  /** DELETE /tasks/:id */
  delete: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"delete"> => ({
    url: buildUrl("/tasks/:id", params, options),
    method: "delete",
  }),
  /** GET /tasks/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions<TaskEditQuery>,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/tasks/:id/edit", params, options),
    method: "get",
  }),
  /** GET /tasks */
  index: (options?: RouteOptions<TaskIndexQuery>): RouteDefinition<"get"> => ({
    url: buildUrl("/tasks", {}, options),
    method: "get",
  }),
  /** GET /tasks/new */
  new: (options?: RouteOptions): RouteDefinition<"get"> => ({
    url: buildUrl("/tasks/new", {}, options),
    method: "get",
  }),
  /** GET /tasks/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions<TaskShowQuery>,
  ): RouteDefinition<"get"> => ({
    url: buildUrl("/tasks/:id", params, options),
    method: "get",
  }),
  /** PATCH /tasks/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<"patch"> => ({
    url: buildUrl("/tasks/:id", params, options),
    method: "patch",
  }),
} as const;
