defmodule Mix.Tasks.TypelizerTest do
  # End to end: `mix typelizer.gen` writes the files, `mix typelizer.check` detects drift.
  use ExUnit.Case, async: false

  @moduletag :tmp_dir

  setup %{tmp_dir: tmp_dir} do
    Mix.shell(Mix.Shell.Process)

    Application.put_env(:typelizer, :output,
      serializers: Path.join(tmp_dir, "serializers"),
      routes: Path.join(tmp_dir, "routes"),
      pages: Path.join(tmp_dir, "pages")
    )

    on_exit(fn ->
      Application.delete_env(:typelizer, :output)
      Mix.shell(Mix.Shell.IO)
    end)

    :ok
  end

  defp gen do
    Mix.Task.rerun("typelizer.gen", [])
    assert_received {:mix_shell, :info, [message]}
    message
  end

  defp check do
    Mix.Task.rerun("typelizer.check", [])
    assert_received {:mix_shell, :info, [message]}
    message
  end

  defp check_drift do
    assert catch_exit(Mix.Task.rerun("typelizer.check", [])) == {:shutdown, 1}
    assert_received {:mix_shell, :error, [report]}
    report
  end

  test "gen writes the files and check passes", %{tmp_dir: tmp_dir} do
    assert gen() == "typelizer: wrote 23 files, 0 unchanged, removed 0 stale files."
    assert File.read!(Path.join(tmp_dir, "serializers/Task.ts")) =~ "export interface Task {"
    assert File.exists?(Path.join(tmp_dir, "pages/tasks/index.props.ts"))
    assert File.exists?(Path.join(tmp_dir, "routes/runtime.ts"))

    assert check() == "typelizer: the generated TypeScript is up to date."
    assert gen() == "typelizer: wrote 0 files, 23 unchanged, removed 0 stale files."
  end

  test "check reports changed, missing and stale files, and gen repairs them", %{tmp_dir: tmp_dir} do
    gen()

    task = Path.join(tmp_dir, "serializers/Task.ts")

    File.write!(
      task,
      String.replace(File.read!(task), "  title: string;\n", "  title: string | null;\n")
    )

    File.rm!(Path.join(tmp_dir, "routes/task.ts"))
    File.mkdir_p!(Path.join(tmp_dir, "pages/old"))

    File.write!(
      Path.join(tmp_dir, "pages/old/page.props.ts"),
      "// Generated by typelizer — do not edit.\n"
    )

    File.write!(Path.join(tmp_dir, "serializers/custom.ts"), "export type Custom = string;\n")

    report = check_drift()

    assert report =~ "typelizer: the generated TypeScript is out of date (3 files):\n"
    assert report =~ "  changed  #{Path.relative_to(task, File.cwd!())}\n"
    assert report =~ "    - #{"  title: string | null;"}\n"
    assert report =~ "    + #{"  title: string;"}"
    assert report =~ ~r"  missing  .*routes/task.ts"
    assert report =~ ~r"  stale    .*pages/old/page.props.ts"
    refute report =~ "custom.ts"
    assert report =~ "Run `mix typelizer.gen` and commit the result."

    assert gen() == "typelizer: wrote 2 files, 21 unchanged, removed 1 stale file."
    refute File.exists?(Path.join(tmp_dir, "pages/old"))

    assert File.read!(Path.join(tmp_dir, "serializers/custom.ts")) ==
             "export type Custom = string;\n"

    assert check() == "typelizer: the generated TypeScript is up to date."
  end

  test "a drift in the Elixir code fails the check", %{tmp_dir: tmp_dir} do
    gen()

    Application.put_env(:typelizer, :type_names, %{MyAppWeb.UserSerializer => "Person"})

    try do
      report = check_drift()
      assert report =~ ~r"missing  .*serializers/Person.ts"
      assert report =~ ~r"stale    .*serializers/User.ts"
      assert report =~ ~r"changed  .*serializers/Task.ts"
    after
      Application.delete_env(:typelizer, :type_names)
    end

    assert File.exists?(Path.join(tmp_dir, "serializers/User.ts"))
  end

  test "gen never overwrites a file it did not generate", %{tmp_dir: tmp_dir} do
    user = Path.join(tmp_dir, "serializers/User.ts")
    File.mkdir_p!(Path.dirname(user))
    File.write!(user, "export interface User { mine: true }\n")

    assert_raise Mix.Error, ~r/User.ts exists and was not generated by typelizer/, fn ->
      Mix.Task.rerun("typelizer.gen", [])
    end

    assert File.read!(user) == "export interface User { mine: true }\n"
    refute File.exists?(Path.join(tmp_dir, "routes"))
  end

  test "generation errors become Mix errors" do
    Application.put_env(:typelizer, :router, String)

    try do
      assert_raise Mix.Error,
                   ~r/^typelizer: config :typelizer, router: String is not a Phoenix router/,
                   fn ->
                     Mix.Task.rerun("typelizer.check", [])
                   end
    after
      Application.delete_env(:typelizer, :router)
    end
  end

  test "the tasks take no arguments" do
    assert_raise Mix.Error, ~r/mix typelizer.gen takes no arguments/, fn ->
      Mix.Task.rerun("typelizer.gen", ["--force"])
    end
  end

  test "prettier: true without Prettier installed fails" do
    Application.put_env(:typelizer, :prettier, true)

    try do
      assert_raise Mix.Error, ~r/Prettier is not installed/, fn ->
        Mix.Task.rerun("typelizer.gen", [])
      end
    after
      Application.delete_env(:typelizer, :prettier)
    end
  end
end
