// Generated by typelizer — do not edit.
// Source: MyAppWeb.TaskController

import type { Comment } from "../../serializers/Comment";
import type {
  CursorPaginated,
  Envelope,
  Paginated,
} from "../../serializers/Envelope";
import type { Task } from "../../serializers/Task";
import type { SharedProps } from "../shared.props";

export interface TasksArchiveProps extends SharedProps {
  tasks: Paginated<Task>;
  feed: CursorPaginated<Comment>;
  summary: Envelope<string>;
}
