// Generated by typelizer — do not edit.
// Source: MyAppWeb.TaskController

import type { Task } from "../../serializers/Task";
import type { SharedProps } from "../shared.props";

export interface TasksIndexProps extends SharedProps {
  tasks: Task[];
  filters: Record<string, unknown>;
  nextCursor: string | null;
  stats?: {
    open: number;
    done: number;
  };
}
