// Generated by typelizer — do not edit.
// Source: MyAppWeb.TaskController

import type { Project } from "../../serializers/Project";
import type { SharedProps } from "../shared.props";

export interface NewTaskProps extends SharedProps {
  statuses: ("todo" | "doing" | "done")[];
  project: Project | null;
}
