// Generated by typelizer — do not edit.
// Source: MyAppWeb.TaskController

import type { Task } from "../../serializers/Task";
import type { SharedProps } from "../shared.props";

export interface TasksShowProps extends SharedProps {
  task: Task;
  canEdit: boolean;
}
