defmodule Typelizer.Serializer.Runtime do
  @moduledoc false
  # Helpers that the code generated by `use Typelizer.Serializer` calls at runtime.

  alias Typelizer.SerializationError

  @doc "Reads a field of the record, or raises a `Typelizer.SerializationError`."
  @spec fetch!(term(), atom(), module()) :: term()
  def fetch!(record, field, serializer) do
    case record do
      %{^field => value} ->
        value

      %{} ->
        raise SerializationError,
              "#{inspect(serializer)}: the record has no field #{inspect(field)}. " <>
                "Got: #{describe(record)}"

      _ ->
        raise SerializationError,
              "#{inspect(serializer)} expects a struct or a map, got: #{inspect(record)}"
    end
  end

  @doc "Serializes the value of a `has_one` field."
  @spec one(term(), module(), keyword(), module(), atom()) :: map() | nil
  def one(nil, _serializer, _opts, _owner, _field), do: nil

  def one(%{__struct__: Ecto.Association.NotLoaded}, _serializer, _opts, owner, field),
    do: not_loaded!(owner, field)

  def one(value, serializer, opts, _owner, _field), do: serializer.serialize(value, opts)

  @doc "Serializes the value of a `has_many` field. `nil` becomes `[]`."
  @spec many(term(), module(), keyword(), module(), atom()) :: [map()]
  def many(nil, _serializer, _opts, _owner, _field), do: []

  def many(%{__struct__: Ecto.Association.NotLoaded}, _serializer, _opts, owner, field),
    do: not_loaded!(owner, field)

  def many(values, serializer, opts, _owner, _field), do: serializer.serialize_many(values, opts)

  @doc "Calls a `value:` function whose arity is not known at compile time."
  @spec call(function(), term(), keyword()) :: term()
  def call(fun, record, _opts) when is_function(fun, 1), do: fun.(record)
  def call(fun, record, opts) when is_function(fun, 2), do: fun.(record, opts)

  def call(other, _record, _opts) do
    raise SerializationError,
          "value: must be a function of arity 1 (record) or 2 (record, opts), got: " <>
            inspect(other)
  end

  defp not_loaded!(owner, field) do
    raise SerializationError,
          "#{inspect(owner)}: the association #{inspect(field)} is not loaded. " <>
            "Preload it before serializing, for example Repo.preload(record, #{inspect(field)})"
  end

  defp describe(%{__struct__: struct}), do: "%#{inspect(struct)}{}"
  defp describe(map), do: "a map with keys #{inspect(Map.keys(map))}"
end
