// Generated by typelizer — do not edit.
// Source: MyAppWeb.DashboardController

import type { AdminTask } from "../serializers/AdminTask";
import type { DashboardStats } from "../serializers/DashboardStats";
import type { SharedProps } from "./shared.props";

export interface DashboardProps extends SharedProps {
  stats: DashboardStats;
  recent: AdminTask[];
}
