// Generated by typelizer — do not edit.
// Source: MyAppWeb.InertiaShared

import type { User } from "../serializers/User";

export interface SharedProps {
  currentUser: User | null;
  locale: string;
  errors: Record<string, string>;
  flash: Record<string, string>;
}
